### PR TITLE
flesh out SmartOS command examples

### PR DESCRIPTION
**Pull request by bixu**

### CODE REVIEW

**Comment by lloydde** [comment]
did u do a diff vs @bahamat #2 ?

**Comment by mikemaccana** [comment]
Thanks @bixu! I merged this manually with @bahamat's commits, there was some overlap. Since oracle docs point to pkgin as being the preferred tool where you've differed I've preferred pkgin. If that's not correct let me know and I'll fix it.

**Comment by bixu** [comment]
Just as an FYI, Oracle has nothing to do with SmartOS, and there’s significant differences now between even the CLI interfaces of SmartOS and Oracle Solaris.

**Comment by mikemaccana** [comment]
Thanks and acknowledged. How much do illumos and SmartOS differ? Is illumos
documentation usable as a reference to SmartOS?

**Comment by bahamat** [comment]
illumos-gate is the kernel and user land base. It's not a system in itself. Much in the same way that Linux is just a kernel, not a complete system. SmartOS, OmniOS and OpenIndiana are three illumos distributions. Just like in Linux or BSD, each has their own additions to illumos, that will for the most part eventually be merged upstream.

In general, anything that relates to illumos itself should pretty much be expected to work across any illumos distro.

For purposes of the rosetta stone, it's probably worth adding OmniOS/OpenIndiana. They're similar enough in most regards that I don't think there would be significant differences from each other. SmartOS, though, does have significant differences them.

**Pull request merged**
